version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: gestao_obras_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: vicius_admin
      POSTGRES_PASSWORD: admin_password_super_secreta
      POSTGRES_DB: gestao_obras
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: